name: Security Scan

on: [push]

jobs:
  security-check:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Securiy tools
        run: pip install bandit
      - name: Run Security check
        run: python security_scan.py
      - name: run Bandit scan
        run: bandit -r .
